version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget"
    directory: "/src/IdentityPasswordGenerator"
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget"
    directory: "/src/IdentityPasswordGenerator.Tests"
    schedule:
      interval: "weekly"
